name: Build and deploy to WordPress.org
on:
  release:
      types: [published]
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

      # Install all composer dependencies for the plugin.
    - name: Install Composer dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        php_version: 7.4

    # Deploy the plugin to WordPress.org
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: ledyer-order-management-for-woocommerce